services:

  app:
    build:
      context: ./
    restart: always
    ports:
      - 8089:80
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    #Development bind mount (comment out for production)
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - 3310:3306
    volumes:
      - db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${MYSQL_RANDOM_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

volumes:
  app:
  db: